name: CI

on:
  pull_request:
    branches: [ dev ]

env:
    TMPDIR: /tmp/flash/
    flash_env: testing

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: flash_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3


    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create required directories and set permissions
        run: |
          mkdir -p /tmp/flash/data/proxy
          chmod -R 777 /tmp/flash

      - name: Setup PHP 8.3.2
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3.2'
          tools: composer:v2.7.2
