name: Mysql connect

on:
  workflow_dispatch:
  push:
    branches: [ add-gha-test ]

jobs:
  connect-test:
    runs-on: ubuntu-latest

    steps:
      - name: check docker version
        run: docker context ls

      - name: check docker version
        run: docker version

      # - name: Create Docker network
      #   run: |
      #     docker network create flash-net

      - name: Start MySQL Container
        run: |
          docker run --name mysql_ci \
          -e MYSQL_ALLOW_EMPTY_PASSWORD=yes \
          -e MYSQL_DATABASE=flash_test \
          -p 3306:3306 \
          -d public.ecr.aws/docker/library/mysql:8.0

      - name: Install MySQL Client
        run: |
          sudo apt update
          sudo apt install net-tools
          sudo apt install -y mysql-client

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup database
        run: |
          mysql -h 127.0.0.1 -u root -e 'CREATE DATABASE IF NOT EXISTS flash_test;'

      - name: Check 3306
        run: |
          sudo netstat -tulnp | grep 3306

      - name: check Docker logs
        run: |
          docker ps

      - name: Test MySQL connection from client container
        run: |
          docker run --rm --add-host=host.docker.internal:host-gateway \
          public.ecr.aws/docker/library/mysql:8.0 \
            mysql -h host.docker.internal -u root -e "USE flash_test; SELECT 1;"

      
